apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-quality-api
  labels:
    app.kubernetes.io/name: data-quality-api
    app.kubernetes.io/component: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: data-quality-api
  template:
    metadata:
      labels:
        app.kubernetes.io/name: data-quality-api
        app.kubernetes.io/component: api
    spec:
      containers:
        - name: data-quality-api
          image: data-quality-api:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          envFrom:
            - configMapRef:
                name: data-quality-api-config
