apiVersion: v1
kind: Service
metadata:
  name: data-quality-api
  labels:
    app.kubernetes.io/name: data-quality-api
    app.kubernetes.io/component: api
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: data-quality-api
  ports:
    - name: http
      port: 8000
      targetPort: 8000
