apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - configmap.yaml

labels:
  - pairs:
      app.kubernetes.io/environment: staging
    includeSelectors: true
    includeTemplates: true

replicas:
  - name: data-quality-api
    count: 1
